spring.application.name=itau

management.endpoints.web.exposure.include=health,info,metrics,swagger-ui

management.endpoint.health.show-details=always

management.info.env.enabled=true
management.info.app.name=Api de Transacoes
management.info.app.version=1.0.0
management.info.app.description=Api responsavel por gerenciar transacoes e estatisticas

management.metrics.tags.application=api-transacoes
management.metrics.enable.all=true

springdoc.show-actuator=true